# Site settings
title: Teeth and Smiles Clinic
email: contact@teethandsmilesclinic.com
url: https://www.teethandsmilesclinic.com
description: "Your Family Dentist"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#000000"
  links: "#219ab3"

# Footer settings
footer: Teeth and Smiles Clinic

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/teethandsmilesclinic
  - title: instagram
    url: https://www.instagram.com/teethandsmilesclinic/

# Build settings
markdown: kramdown
permalink: pretty
